### ISSUE TITLE
format the output SQL in sqlfrog web app(http://107.170.101.241:8080/sqlfrog/)

### ISSUE THREAD

**Issue by sqlparser** [sqlparser/sqlfrog#15]
Please use APIs of this web service to format the output SQL in sqlfrog web app

https://github.com/sqlparser/sql-pretty-printer/wiki/SQL-FaaS#2-api

**Comment by sqlparser** [comment]
Please double the size of the input and output SQL area.

**Comment by cnfree** [comment]
Updated the sqlfrog web application, please force the browser to clear js cache.
