### ISSUE TITLE
Converting with type casting

### ISSUE THREAD

**Issue by githusbandry** [sqlparser/sqlfrog#21]
Could you please add support for converting queries with casting as shown below:

    SELECT
      a.schl_hol_cd,
      b.descr,
      TRUNC(extract(epoch from (a.strt_date::timestamp - TO_DATE(:sqlZeroDate)))/60),
      TRUNC(extract(epoch from (a.end_date::timestamp  - TO_DATE(:sqlZeroDate)))/60)
    FROM
      tb_schl_hol     a,
      tb_schl_hol_prd b
    WHERE
      a.schl_hol_cd = b.schl_hol_cd AND
      a.strt_date  <= TO_DATE(:sqlToDate,   'YYYY-MM-DD') AND
      a.end_date   >= TO_DATE(:sqlFromDate, 'YYYY-MM-DD')
    ORDER BY
      strt_date;

Thank you ;)

**Comment by cnfree** [comment]
Simply implemented it.

Oracle
```
select 
a.schl_hol_cd,b.descr,trunc((to_date((a.strt_date - TO_DATE(sqlZeroDate))) - to_date('19700101','YYYYMMDD')) * 86400 / 60),trunc((to_date((a.end_date - TO_DATE(sqlZeroDate))) - to_date('19700101','YYYYMMDD')) * 86400 / 60)
 from 
tb_schl_hol a,
tb_schl_hol_prd b
 where a.schl_hol_cd = b.schl_hol_cd  and  a.strt_date <= TO_DATE(sqlToDate,'YYYY-MM-DD')  and  a.end_date >= TO_DATE(sqlFromDate,'YYYY-MM-DD')
 order  by strt_date
```

SQL Server(doesn't support epoch  now)
```
select 
a.schl_hol_cd,b.descr,floor(datepart(second,(a.strt_date - convert( datetime ,sqlZeroDate))) / 60),floor(datepart(second,(a.end_date - convert( datetime ,sqlZeroDate))) / 60)
 from 
tb_schl_hol a,
tb_schl_hol_prd b
 where a.schl_hol_cd = b.schl_hol_cd  and  a.strt_date <= convert( datetime ,sqlToDate)  and  a.end_date >= convert( datetime ,sqlFromDate)
 order  by strt_date
```
@githusbandry Which db does you want to convert?

**Comment by githusbandry** [comment]
I forgot to mention it's Oracle to PostgreSQL conversion - thanks.
