### ISSUE TITLE
PostgreSQL subqueries

### ISSUE THREAD

**Issue by mmusta** [sqlparser/sqlfrog#22]
Hi !

PostgreSQL subqueries must be include alias;

Ex:  
Oracle -  select * from (select * from c) 
PostgreSQL-  select * from (select * from c)  as aliasName

**Comment by sqlparser** [comment]
Do you have any suggestions about the name of the new alias?

**Comment by cnfree** [comment]
Fixed it.

Simply add an alias ‘t’ for the subquery table.
