### ISSUE TITLE
Converting SQL containing CASE expression

### ISSUE THREAD

**Issue by githusbandry** [sqlparser/sqlfrog#23]
The query below containing Oracle joins failed to convert with sqlFrog.

...
File: test.sql, syntax error, state:589(10102) near: )(14,58)
no_root_node(-1000) near: no root node(0,0)
...

Error message suggests it couldn't process the CASE expression.
Could you please review and provide a resolution - thanks.

    SELECT
      rstr.empl_nbr,
      rstr.actv_typ,
      NVL((SELECT CASE
             WHEN rstr.actv_typ = 0 THEN rstr.prng_cd
             WHEN rstr.actv_typ = 1 THEN NVL(rsrv.rsrv_dty_cd, 'Reserve Duty ?')
             WHEN rstr.actv_typ = 2 THEN NVL(grnd.grnd_dty_cd, 'Ground Duty ?')
             WHEN rstr.actv_typ = 3 THEN NVL(crse.crse_cd, 'Course ?')
             WHEN rstr.actv_typ = 4 THEN NVL(rnwl.rnwl_dty_cd, 'Renewal ?')
             WHEN rstr.actv_typ = 5 THEN rstr.leav_cd
             WHEN rstr.actv_typ = 6 THEN 'Day Off'
             WHEN rstr.actv_typ = 7 THEN 'Open Day'
             WHEN rstr.actv_typ = 8 THEN 'Flight'
             WHEN rstr.actv_typ = 9 THEN 'Instructor' END), 'UNKNOWN'),
      TO_CHAR(rstr.strt_date, 'YYYY-MM-DD HH24:MI'),
      TO_CHAR(rstr.end_Date,  'YYYY-MM-DD HH24:MI'),
      TO_CHAR(NVL(rstr.unass_notify_date, :sqlZeroDate), 'YYYY-MM-DD HH24:MI'),
      unass_notify_usr_id,
      unassgnd_usr_id,
      TO_CHAR(NVL(rstr.unassgnd_date, :sqlZeroDate), 'YYYY-MM-DD HH24:MI'),
      prng_lvl,
      empl_typ
    FROM
      tb_rstr_actv_hist rstr,
      tb_rsrv_actv rsrv,
      tb_grnd_actv grnd,
      tb_rnwl_actv rnwl,
      tb_crse_actv crse
    WHERE
      rstr.crw_grp_cd  = :crwUser.sqlCrwGrpCd    AND
      rstr.strt_date  <= :sqlEnd                               AND
      rstr.end_date   >= :sqlStart                            AND
      rstr.rsrv_actv_fk  = rsrv.rsrv_actv_key     (+)  AND
      rstr.grnd_actv_fk  = grnd.grnd_actv_key (+)  AND
      rstr.rnwl_actv_fk  = rnwl.rnwl_actv_key   (+)  AND
      rstr.crse_actv_key = crse.crse_actv_key (+)
    ORDER BY
      1, 4, 6;

**Comment by sqlparser** [comment]
It seems the from clause is missing in the following subquery, please make sure the syntax of this SQL is valid.

```sql
(SELECT CASE
         WHEN rstr.actv_typ = 0 THEN rstr.prng_cd
         WHEN rstr.actv_typ = 1 THEN NVL(rsrv.rsrv_dty_cd, 'Reserve Duty ?')
         WHEN rstr.actv_typ = 2 THEN NVL(grnd.grnd_dty_cd, 'Ground Duty ?')
         WHEN rstr.actv_typ = 3 THEN NVL(crse.crse_cd, 'Course ?')
         WHEN rstr.actv_typ = 4 THEN NVL(rnwl.rnwl_dty_cd, 'Renewal ?')
         WHEN rstr.actv_typ = 5 THEN rstr.leav_cd
         WHEN rstr.actv_typ = 6 THEN 'Day Off'
         WHEN rstr.actv_typ = 7 THEN 'Open Day'
         WHEN rstr.actv_typ = 8 THEN 'Flight'
         WHEN rstr.actv_typ = 9 THEN 'Instructor' END)
```

**Comment by githusbandry** [comment]
Yes you're right. It was omitted after hand conversion for Postgres which doesn't require FROM clause. Sorry for the inconvenience I'll double check prior submissions next time  - thanks.
