### ISSUE TITLE
LIMIT for result set (PostgreSQL)

### ISSUE THREAD

**Issue by githusbandry** [sqlparser/sqlfrog#24]
Hi, could you please add conversion support for PostgreSQL LIMIT
which can be used in place of Oracle's rownum, example follows - thanks

ORACLE:

      SELECT NVL(u.val,d.dflt_val)
      FROM tb_pac_param_val u,
           tb_pac_param d
      WHERE d.var = u.var(+) AND
      rownum <= 100 ;  

POSTGRESQL:

      SELECT NVL(u.val,d.dflt_val)
      FROM tb_pac_param_val u,
           tb_pac_param d
      WHERE d.var = u.var(+)  
      LIMIT 100;

**Comment by cnfree** [comment]
Implemented it, and fixed a bug of TScriptGeneratorVisitor, please merge it at gsp parser @sqlparser

**Comment by cnfree** [comment]
Fixed both java and c# versions.
