### ISSUE TITLE
Can you check this query, throws null pointer exception

### ISSUE THREAD

**Issue by mmusta** [sqlparser/sqlfrog#25]
SELECT COUNT(L.COL5) AS SUM FROM TABLE1 L,TABLE2 A, TABLE3 U, TABLE4 P 
WHERE L.COL1 = A.COL1 AND L.COL2 = :KEY1 AND NVL(L.COL4,'H') = :COL4 AND 
NVL(A.COL2, 'H') = 'E' AND U.COL3 = 
DECODE(A.COL1, CAST(:KEY2 AS NUMBER), L.COL2, A.COL1) AND U.PR_KEY = P.PR_KEY(+)

**Comment by sqlparser** [comment]
@cnfree  @zxhehe

**Comment by cnfree** [comment]
Fixed it.
