### ISSUE TITLE
COALESCE()

### ISSUE THREAD

**Issue by mmusta** [sqlparser/sqlfrog#26]
Hi, could you please add conversion support for Oracle NVL() to  PostgreSQL COALESCE() function

ORACLE:
Format: NVL( argument_1, replace_with )
Ex: SELECT NVL(col1, 0) FROM DUAL 

POSTGRESQL:
Format COALESCE (argument_1, argument_2, …)
Ex: SELECT COALESCE (col1, 0)

**Comment by sqlparser** [comment]
@cnfree

**Comment by cnfree** [comment]
Implemented it.
