### ISSUE TITLE
ANSI SQL compatible checker: copying structure

### ISSUE THREAD

**Issue by sqlparser** [sqlparser/sqlfrog#3]
Please check this page:
https://github.com/sqlparser/sqlfrog/wiki/Copying-structure

**Comment by cnfree** [comment]
gsp core can't handle LIKE clause of ANSI SQL and DB2 SQL.

**Comment by sqlparser** [comment]
upload gsp core lib 1.9.3.6 under master/lib, able to handle DB2
```sql
CREATE TABLE t2 LIKE t1 INCLUDING DEFAULTS
```

Please just ignore the ANSI SQL currently.

**Comment by cnfree** [comment]
Implemented it.
